#Redis配置
spring:
  redis:
    password: 12345678    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes: 10.19.115.195:7019,10.19.115.195:7020,10.19.115.188:7019,10.19.115.188:7020,10.19.115.190:7019,10.19.115.195:7020
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接