#Redis配置
spring:
  redis:
    password: 123456    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    cluster:
      max-redirects: 2  # 获取失败 最大重定向次数
      nodes: 192.168.149.128:6370,192.168.149.128:6371,192.168.149.129:6370,192.168.149.129:6371,192.168.149.130:6370,192.168.149.130:6371
    jedis: 
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
          